stages:
  process_data:
    cmd: python src/process_data.py
    deps:
    - data/raw/us_accident.csv
    - src/process_data.py
    outs:
    - data/processed/us_accident_clean.csv
  validate:
    cmd: python src/validate.py
    deps:
    - data/processed/us_accident_clean.csv
    - src/validate.py
    outs:
    - reports/validation.txt
